-- ---------------------------------------------------------------------------
--  Reverse 02_foreign_keys.sql.
--
--  Two steps are required.  MariaDB creates a secondary index for each foreign
--  key that has no usable index already, and DROP FOREIGN KEY does NOT remove
--  that index -- it survives the constraint.  Dropping the constraints alone
--  leaves the storage and load cost behind, so the indexes are dropped too.
--
--  IF EXISTS is used on the index drops because InnoDB reuses an existing
--  index where one covers the foreign key columns (a primary key prefix, for
--  example), in which case no separate index was ever created.
-- ---------------------------------------------------------------------------

USE tpcds;

-- step 1: drop the constraints ----------------------------------------------

ALTER TABLE call_center DROP FOREIGN KEY IF EXISTS cc_d1;
ALTER TABLE call_center DROP FOREIGN KEY IF EXISTS cc_d2;
ALTER TABLE catalog_page DROP FOREIGN KEY IF EXISTS cp_d1;
ALTER TABLE catalog_page DROP FOREIGN KEY IF EXISTS cp_d2;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_cc;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_cp;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_i;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_r;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_a1;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_cd1;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_c1;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_hd1;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_d1;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_i_2;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_a2;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_cd2;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_c2;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_hd2;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_sm;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_w2;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_b_a;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_b_cd;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_b_c;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_b_hd;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_cc;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_cp;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_i;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_p;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_s_a;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_s_cd;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_s_c;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_d1;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_s_hd;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_sm;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_d2;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_t;
ALTER TABLE catalog_sales DROP FOREIGN KEY IF EXISTS cs_w;
ALTER TABLE customer DROP FOREIGN KEY IF EXISTS c_a;
ALTER TABLE customer DROP FOREIGN KEY IF EXISTS c_cd;
ALTER TABLE customer DROP FOREIGN KEY IF EXISTS c_hd;
ALTER TABLE customer DROP FOREIGN KEY IF EXISTS c_fsd;
ALTER TABLE customer DROP FOREIGN KEY IF EXISTS c_fsd2;
ALTER TABLE household_demographics DROP FOREIGN KEY IF EXISTS hd_ib;
ALTER TABLE inventory DROP FOREIGN KEY IF EXISTS inv_d;
ALTER TABLE inventory DROP FOREIGN KEY IF EXISTS inv_i;
ALTER TABLE inventory DROP FOREIGN KEY IF EXISTS inv_w;
ALTER TABLE promotion DROP FOREIGN KEY IF EXISTS p_end_date;
ALTER TABLE promotion DROP FOREIGN KEY IF EXISTS p_i;
ALTER TABLE promotion DROP FOREIGN KEY IF EXISTS p_start_date;
ALTER TABLE store DROP FOREIGN KEY IF EXISTS s_close_date;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_a;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_cd;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_c;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_hd;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_i;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_r;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_ret_d;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_t;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_s;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_a;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_cd;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_c;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_hd;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_i;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_p;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_d;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_t;
ALTER TABLE store_sales DROP FOREIGN KEY IF EXISTS ss_s;
ALTER TABLE web_page DROP FOREIGN KEY IF EXISTS wp_ad;
ALTER TABLE web_page DROP FOREIGN KEY IF EXISTS wp_cd;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_i;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_r;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ref_a;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ref_cd;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ref_c;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ref_hd;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ret_d;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ret_t;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ret_a;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ret_cd;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ret_c;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_ret_cd_2;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_wp;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_b_a;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_b_cd;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_b_c;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_b_cd_2;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_i;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_p;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_s_a;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_s_cd;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_s_c;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_s_d;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_s_hd;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_sm;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_d2;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_t;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_w2;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_wp;
ALTER TABLE web_sales DROP FOREIGN KEY IF EXISTS ws_ws;
ALTER TABLE web_site DROP FOREIGN KEY IF EXISTS web_d1;
ALTER TABLE web_site DROP FOREIGN KEY IF EXISTS web_d2;
ALTER TABLE customer DROP FOREIGN KEY IF EXISTS c_d;
ALTER TABLE store_returns DROP FOREIGN KEY IF EXISTS sr_i_tn;
ALTER TABLE catalog_returns DROP FOREIGN KEY IF EXISTS cr_i_on;
ALTER TABLE web_returns DROP FOREIGN KEY IF EXISTS wr_i_on;
ALTER TABLE web_page DROP FOREIGN KEY IF EXISTS wp_c;

-- step 2: drop the indexes MariaDB created for them -------------------------

ALTER TABLE call_center DROP INDEX IF EXISTS cc_d1;
ALTER TABLE call_center DROP INDEX IF EXISTS cc_d2;
ALTER TABLE catalog_page DROP INDEX IF EXISTS cp_d1;
ALTER TABLE catalog_page DROP INDEX IF EXISTS cp_d2;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_cc;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_cp;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_i;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_r;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_a1;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_cd1;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_c1;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_hd1;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_d1;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_i_2;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_a2;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_cd2;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_c2;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_hd2;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_sm;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_w2;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_b_a;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_b_cd;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_b_c;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_b_hd;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_cc;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_cp;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_i;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_p;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_s_a;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_s_cd;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_s_c;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_d1;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_s_hd;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_sm;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_d2;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_t;
ALTER TABLE catalog_sales DROP INDEX IF EXISTS cs_w;
ALTER TABLE customer DROP INDEX IF EXISTS c_a;
ALTER TABLE customer DROP INDEX IF EXISTS c_cd;
ALTER TABLE customer DROP INDEX IF EXISTS c_hd;
ALTER TABLE customer DROP INDEX IF EXISTS c_fsd;
ALTER TABLE customer DROP INDEX IF EXISTS c_fsd2;
ALTER TABLE household_demographics DROP INDEX IF EXISTS hd_ib;
ALTER TABLE inventory DROP INDEX IF EXISTS inv_d;
ALTER TABLE inventory DROP INDEX IF EXISTS inv_i;
ALTER TABLE inventory DROP INDEX IF EXISTS inv_w;
ALTER TABLE promotion DROP INDEX IF EXISTS p_end_date;
ALTER TABLE promotion DROP INDEX IF EXISTS p_i;
ALTER TABLE promotion DROP INDEX IF EXISTS p_start_date;
ALTER TABLE store DROP INDEX IF EXISTS s_close_date;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_a;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_cd;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_c;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_hd;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_i;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_r;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_ret_d;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_t;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_s;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_a;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_cd;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_c;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_hd;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_i;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_p;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_d;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_t;
ALTER TABLE store_sales DROP INDEX IF EXISTS ss_s;
ALTER TABLE web_page DROP INDEX IF EXISTS wp_ad;
ALTER TABLE web_page DROP INDEX IF EXISTS wp_cd;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_i;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_r;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ref_a;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ref_cd;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ref_c;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ref_hd;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ret_d;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ret_t;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ret_a;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ret_cd;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ret_c;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_ret_cd_2;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_wp;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_b_a;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_b_cd;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_b_c;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_b_cd_2;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_i;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_p;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_s_a;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_s_cd;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_s_c;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_s_d;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_s_hd;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_sm;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_d2;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_t;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_w2;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_wp;
ALTER TABLE web_sales DROP INDEX IF EXISTS ws_ws;
ALTER TABLE web_site DROP INDEX IF EXISTS web_d1;
ALTER TABLE web_site DROP INDEX IF EXISTS web_d2;
ALTER TABLE customer DROP INDEX IF EXISTS c_d;
ALTER TABLE store_returns DROP INDEX IF EXISTS sr_i_tn;
ALTER TABLE catalog_returns DROP INDEX IF EXISTS cr_i_on;
ALTER TABLE web_returns DROP INDEX IF EXISTS wr_i_on;
ALTER TABLE web_page DROP INDEX IF EXISTS wp_c;
